sonar.projectKey=Ziol3k_projektowanie-obiektowe
sonar.organization=ziol3k
sonar.projectName=zadanie_6

sonar.sources=zadanie_3/singleton-task/src,zadanie_4,zadanie_5
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/coverage/**,**/*.test.*,**/*_test.go,**/.husky/**,**/package-lock.json

sonar.coverage.exclusions=**